Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 1000000
  traces: 
    - ultraram_study/traces/429.mcf

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648


MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR5
    org:
      preset: DDR5_16Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: DDR5_3200AN
    RFM:
      BRC: 2

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: NoRefresh
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
    plugins:
      - ControllerPlugin:
          impl: CommandCounter
          path: ./haha.txt
  AddrMapper:
    impl: RoBaRaCoCh
