Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 10000000
  traces: 
    - example_inst.trace

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: URAM4
    org:
      preset: URAM4_8Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: URAM4_2400R 
    RFM:
      BRC: 2

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: NoRefresh
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
    plugins:
      - ControllerPlugin:
          impl: CommandCounter
          path: ./should_be_replaced.txt

  AddrMapper:
    impl: RoBaRaCoCh
