Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 100000
  traces: 
    - traces/429.mcf

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: URAM5
    org:
      preset: URAM5_8Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: URAM5_3200AN
    scales:
    RFM:
      BRC: 2

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: NoRefresh
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4

  AddrMapper:
    impl: RoBaRaCoCh
