Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 100000000
  traces: 
    - traces/429.mcf

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: URAM5
    drampower_enable: true
    org:
      preset: URAM5_8Gb_x8
      channel: 2
      rank: 2
    timing:
      preset: URAM5_8800AN
    RFM:
      BRC: 2
    voltage:
      preset: Default
    current:
      preset: Default

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: NoRefresh
    RowPolicy:
      impl: OpenRowPolicy
      cap: 8

  AddrMapper:
    impl: MOP4CLXOR
